version: "3.2" 

services: 
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "password"
    ports:
      - 8998:5432

  adminer:
    build: 
      context: ./adminer
    ports:
      - 8999:8080