version: "3.2" 

ERROR - please fill up the <insert-here*> parts

services: 
  db:
    image: postgres
    environment:
      POSTGRES_USER: bowling
      POSTGRES_PASSWORD: <insert-here-password>

  adminer:
    build: 
      context: ./adminer
    ports:
      - 8999:8080
  
  bowling:
    image: gcali/bowling
    environment:
      NODE_ENV: production
      DATABASE_HOST: db
      DATABASE_PASSWORD: <insert-here-password>
      DATABASE_PORT: 5432 
